name: Auto Green Graph

on:
  schedule:
    # Runs everyday at 04:45 UTC which is 10:15 AM IST 
    # (Avoids heavy traffic delays at exact hourly marks)
    - cron: '45 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update Date File
        run: |
          echo "Solved DSA problems on: $(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S IST')" >> dsa-progress.txt
          git config user.name "Danish Meraj"
          git config user.email "danishmeraj385@gmail.com"
          git add dsa-progress.txt
          git commit -m "Daily DSA Practice: $(TZ='Asia/Kolkata' date +'%Y-%m-%d')"
          git push origin main
